from __future__ import annotations

import json
import pickle
import random
import string
import time
from pathlib import Path

import numpy as np
import torch
from models.base_hmm import BaseHMMModel
from utils.constants import trained_model_path, trained_model_metadata_path
from utils.setup_logger import get_logger

logger = get_logger("mixture_hmm")


class MixtureHMM:
    """
    Mixture of HMMs.

    Each sequence is generated by one of C component HMMs, chosen from
    a categorical prior: P(c) = mixing_weights[c].

    Unlike factorial HMM (which mixes at every timestep), this is a
    sequence-level mixture — each sequence belongs to exactly one component.

    EM:
      E-step: compute responsibilities r[n,c] = P(c | x_n) for each sequence
              and standard posteriors (gamma, xi) per component.
      M-step: update mixing weights and each component's parameters,
              weighted by responsibilities.
    """

    def __init__(
        self,
        vocab_size: int,
        num_components: int,
        num_states: int,
        device: str = "cpu",
        initial_initializer: BaseHMMModel.InitializerName = "zeros",
        transition_initializer: BaseHMMModel.InitializerName = "zeros",
        emission_initializer: BaseHMMModel.InitializerName = "zeros",
    ):
        self.vocab_size = vocab_size
        self.num_components = num_components
        self.num_states = num_states
        self.device = device
        self.initial_initializer_name = initial_initializer
        self.transition_initializer_name = transition_initializer
        self.emission_initializer_name = emission_initializer
        self.iterations_run = 0
        self.final_log_likelihood = None
        self.fit_time = None

        # Mixing weights (log-space logits)
        self.mixing_logits = torch.zeros(num_components, device=device)

        # One BaseHMM per component
        self.component_hmms: list[BaseHMMModel] = []
        for _ in range(num_components):
            self.component_hmms.append(
                BaseHMMModel(
                    vocab_size=vocab_size,
                    num_states=num_states,
                    device=device,
                    initial_initializer=initial_initializer,
                    transition_initializer=transition_initializer,
                    emission_initializer=emission_initializer,
                )
            )

    @property
    def log_mixing_weights(self) -> torch.Tensor:
        return torch.nn.functional.log_softmax(self.mixing_logits, dim=0)  # [C]

    def get_cleaned_data(self, data: list[np.array]) -> list[torch.Tensor]:
        return [
            seq.detach().clone().to(dtype=torch.long, device=self.device)
            if isinstance(seq, torch.Tensor)
            else torch.tensor(seq, dtype=torch.long, device=self.device)
            for seq in data
        ]

    def _compute_responsibilities(self, data: list[torch.Tensor]) -> torch.Tensor:
        """
        Compute log responsibilities: log r[n, c] = log P(c) + log P(x_n | c) - log P(x_n)
        Returns: [N, C] log-responsibilities
        """
        N = len(data)
        C = self.num_components
        log_w = self.log_mixing_weights  # [C]

        log_joint = torch.zeros(N, C, device=self.device)  # log P(c) + log P(x_n | c)
        for c, hmm in enumerate(self.component_hmms):
            for n, seq in enumerate(data):
                alpha = hmm._forward(seq)  # [T, K]
                log_joint[n, c] = log_w[c] + torch.logsumexp(alpha[-1], dim=0)

        # Normalize: log r[n,c] = log_joint[n,c] - logsumexp(log_joint[n,:])
        log_resp = log_joint - torch.logsumexp(log_joint, dim=1, keepdim=True)  # [N, C]
        return log_resp

    def _e_step(self, data: list[torch.Tensor]) -> tuple[torch.Tensor, list[list[dict]]]:
        """
        E-step: compute responsibilities and per-component posteriors.
        Returns:
            log_resp: [N, C] log-responsibilities
            component_posteriors: list of C lists, each containing N dicts with gamma/xi
        """
        log_resp = self._compute_responsibilities(data)  # [N, C]

        component_posteriors = []
        for c, hmm in enumerate(self.component_hmms):
            posteriors = []
            for seq in data:
                alpha = hmm._forward(seq)
                beta = hmm._backward(seq)
                gamma = hmm._compute_gamma(alpha, beta)
                xi = hmm._compute_xi(seq, alpha, beta)
                posteriors.append({
                    'log_alpha': alpha,
                    'log_beta': beta,
                    'log_gamma': gamma,
                    'log_xi': xi,
                })
            component_posteriors.append(posteriors)

        return log_resp, component_posteriors

    def _m_step(self, data: list[torch.Tensor], log_resp: torch.Tensor,
                component_posteriors: list[list[dict]]) -> None:
        """
        M-step: update mixing weights and each component's parameters,
        weighted by responsibilities.
        """
        resp = torch.exp(log_resp)  # [N, C]

        # Update mixing weights: sum of responsibilities
        self.mixing_logits = torch.log(resp.sum(dim=0) / resp.sum())

        # Update each component's parameters with weighted posteriors
        for c, hmm in enumerate(self.component_hmms):
            posteriors = component_posteriors[c]
            w = resp[:, c]  # [N] weights for this component

            # Weighted initial
            gamma_0 = torch.stack([post['log_gamma'][0] for post in posteriors])  # [N, K]
            weighted_gamma_0 = torch.exp(gamma_0) * w.unsqueeze(1)  # [N, K]
            init_probs = weighted_gamma_0.sum(dim=0)
            init_probs = init_probs / init_probs.sum()
            hmm.initial_logits.data = torch.log(init_probs)

            # Weighted transitions
            sum_xi = torch.zeros(hmm.num_states, hmm.num_states, device=self.device)
            sum_gamma = torch.zeros(hmm.num_states, device=self.device)
            for n, post in enumerate(posteriors):
                xi = torch.exp(post['log_xi'])    # [T-1, K, K]
                gamma = torch.exp(post['log_gamma'])  # [T, K]
                sum_xi += w[n] * xi.sum(dim=0)
                sum_gamma += w[n] * gamma[:-1].sum(dim=0)
            hmm.transition_logits.data = torch.log(sum_xi / sum_gamma.unsqueeze(1))

            # Weighted emissions
            sum_gamma_obs = torch.zeros(hmm.num_states, self.vocab_size, device=self.device)
            sum_gamma_total = torch.zeros(hmm.num_states, device=self.device)
            for n, (seq, post) in enumerate(zip(data, posteriors)):
                gamma = torch.exp(post['log_gamma'])  # [T, K]
                for t, obs in enumerate(seq):
                    sum_gamma_obs[:, obs] += w[n] * gamma[t]
                sum_gamma_total += w[n] * gamma.sum(dim=0)
            hmm.emission_logits.data = torch.log(sum_gamma_obs / sum_gamma_total.unsqueeze(1))

    def fit(self, data: list[np.array], max_iteration: int, delta_likelyhood: float):
        logger.info(f"Starting EM for MixtureHMM with {self.num_components} components, "
                     f"max {max_iteration} iterations")
        start_time = time.time()
        prev_ll: float | None = None
        cleaned_data = self.get_cleaned_data(data)
        for iteration in range(int(max_iteration)):
            log_resp, component_posteriors = self._e_step(cleaned_data)
            self._m_step(cleaned_data, log_resp, component_posteriors)
            new_ll = self.log_likelihood(cleaned_data)
            logger.info(f"Iteration {iteration}: log-likelihood = {new_ll:.2f}")
            if prev_ll is not None and abs(new_ll - prev_ll) < delta_likelyhood:
                logger.info(f"Converged at iteration {iteration}")
                self.iterations_run = iteration + 1
                break
            prev_ll = new_ll
        else:
            self.iterations_run = int(max_iteration)
        self.final_log_likelihood = new_ll
        self.fit_time = time.time() - start_time

    def log_likelihood(self, data: list[torch.Tensor]) -> float:
        log_w = self.log_mixing_weights  # [C]
        total_ll = 0.0
        for seq in data:
            seq = seq if isinstance(seq, torch.Tensor) else torch.tensor(seq, dtype=torch.long, device=self.device)
            log_components = torch.zeros(self.num_components, device=self.device)
            for c, hmm in enumerate(self.component_hmms):
                alpha = hmm._forward(seq)
                log_components[c] = log_w[c] + torch.logsumexp(alpha[-1], dim=0)
            total_ll += torch.logsumexp(log_components, dim=0).item()
        return total_ll

    def predict_missing(self, sequence: list[int], mask_index: int) -> int:
        seq = torch.tensor(sequence, dtype=torch.long, device=self.device)
        # Compute responsibilities for this sequence
        log_w = self.log_mixing_weights
        log_comp = torch.zeros(self.num_components, device=self.device)
        for c, hmm in enumerate(self.component_hmms):
            alpha = hmm._forward(seq)
            log_comp[c] = log_w[c] + torch.logsumexp(alpha[-1], dim=0)
        log_resp = log_comp - torch.logsumexp(log_comp, dim=0)  # [C]
        resp = torch.exp(log_resp)

        # Weight each component's prediction
        log_vocab_scores = torch.zeros(self.vocab_size, device=self.device)
        for c, hmm in enumerate(self.component_hmms):
            alpha = hmm._forward(seq)
            beta = hmm._backward(seq)
            gamma = hmm._compute_gamma(alpha, beta)
            state_post = torch.exp(gamma[mask_index])  # [K]
            log_vocab_scores += resp[c] * (state_post.unsqueeze(1) * hmm.log_emission_probs).sum(dim=0)

        return torch.argmax(log_vocab_scores).item()

    def perplexity(self, dataset: list[list[int]]) -> float:
        cleaned = self.get_cleaned_data(dataset)
        total_ll = self.log_likelihood(cleaned)
        total_tokens = sum(len(seq) for seq in cleaned)
        return np.exp(-total_ll / total_tokens)

    def dump(self) -> None:
        logger.info("Dumping model and metadata...")
        random_id = ''.join(random.choices(string.ascii_letters + string.digits, k=6))
        model_name = f"m_{random_id}"
        metadata = {
            "model_type": self.__class__.__name__,
            "vocab_size": self.vocab_size,
            "num_states": self.num_states,
            "num_components": self.num_components,
            "device": self.device,
            "initial_initializer": self.initial_initializer_name,
            "transition_initializer": self.transition_initializer_name,
            "emission_initializer": self.emission_initializer_name,
            "iterations_run": self.iterations_run,
            "final_log_likelihood": self.final_log_likelihood,
            "fit_time": self.fit_time,
        }
        Path(f'{trained_model_metadata_path}/{model_name}.json').write_text(json.dumps(metadata))
        with open(f"{trained_model_path}/{model_name}.pkl", "wb") as f:
            pickle.dump(self, f)
